### ISSUE TITLE
Not working for kernel 5.15.0-27-generic

### ISSUE THREAD

**Issue by danielkucera** [UncleGrumpy/spi-ch341-usb#2]
The driver is loaded correctly but it doesn't create /dev/spidev..
I've patched it to display device name:
```
diff --git a/spi-ch341-usb.c b/spi-ch341-usb.c
index 9241a8b..7377214 100644
--- a/spi-ch341-usb.c
+++ b/spi-ch341-usb.c
@@ -641,8 +641,8 @@ static int ch341_spi_probe (struct ch341_device* ch341_dev)
         ch341_spi_devices[i].bus_num = ch341_dev->master->bus_num;
         if ((ch341_dev->slaves[i] = spi_new_device(ch341_dev->master, &ch341_spi_devices[i])))
         {
-            DEV_INFO (CH341_IF_ADDR, "SPI device /dev/spidev%d.%d created", 
-                      ch341_dev->master->bus_num, ch341_spi_devices[i].chip_select);
+            DEV_INFO (CH341_IF_ADDR, "SPI device %s created", 
+                      dev_name(&ch341_dev->slaves[i]->dev));
             ch341_spi_set_cs (ch341_dev->slaves[i], false);
         }
     }
```
the result is:
```
[383703.332996] spi-ch341-usb 2-2:1.0: ch341_cfg_probe: output cs0 SPI slave with cs=0
[383703.333001] spi-ch341-usb 2-2:1.0: ch341_cfg_probe: output cs1 SPI slave with cs=1
[383703.333002] spi-ch341-usb 2-2:1.0: ch341_cfg_probe: output cs2 SPI slave with cs=2
[383703.333004] spi-ch341-usb 2-2:1.0: ch341_cfg_probe: input  gpio4 gpio=0 irq=0 (hwirq)
[383703.333006] spi-ch341-usb 2-2:1.0: ch341_cfg_probe: input  gpio5 gpio=1 irq=1 
[383703.334457] spi-ch341-usb 2-2:1.0: ch341_spi_probe: SPI master connected to SPI bus 0
[383703.334543] spi-ch341-usb 2-2:1.0: ch341_spi_probe: SPI device spi0.0 created
[383703.334659] spi-ch341-usb 2-2:1.0: ch341_spi_probe: SPI device spi0.1 created
[383703.334754] spi-ch341-usb 2-2:1.0: ch341_spi_probe: SPI device spi0.2 created
[383703.341329] spi-ch341-usb 2-2:1.0: ch341_usb_probe: connected
[383703.341411] usbcore: registered new interface driver spi-ch341-usb
```

I tried googling what changed, I only found this and it doesn't provide an easy solution:
https://forum.armbian.com/topic/20033-51525-breaks-spi-on-nanopi-neo-and-does-not-create-devspidev00/

my uname:
```
Linux silverhorse 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Can you please have a look on this?

**Comment by danielkucera** [comment]
This might shed some light into it:
https://github.com/armbian/build/pull/3737

**Comment by UncleGrumpy** [comment]
Thank you for the information. I will look into it as soon as I have a chance. The spidev should be mounted in dev by the udev rules.

also a note of warning, I assume you are using this for a PineDio-USB dongle… I have not been able to correctly map the GPIO pins from the driver to the internal pins of the sx1262 yet… 
In the meantime there I also have a working fork here:

https://codeberg.org/Winford

There is also a fork of JF002’s LoRa-communicator app that works as a normal user (without needing sudo) that has been submitted upstream, but hasn’t been merged yet… but when it is you should switch to his repo… 
I still plan on figuring out the pin correlations for this fork, because it is much closer to the upstream spi-ch341-usb. the fork jf002 based his off of is heavily modified and has invisible Unicode characters and other “questionable” patches that are not in the upstream repo and make it much harder (at least for me) to follow what the code is actually doing…

**Comment by danielkucera** [comment]
No, I am using with a CH431A programmer:
![image](https://user-images.githubusercontent.com/1734256/170275209-155668a4-d0d9-4433-ad51-d53a53bc83c8.png)

and I just needed to read the readme properly:
https://github.com/UncleGrumpy/spi-ch341-usb#usage-from-user-space

After this, the spidev0.0 was created and I could then use with my python script using spidev module.

**Comment by UncleGrumpy** [comment]
If you are looking for an up to date driver for a generic or general purpose spi-ch341-usb device you should use the [dimich-dmb fork](https://github.com/dimich-dmb/spi-ch341-usb) he does a really good job keeping it up to date and makes improvements to its functionality. That is the repo I am basing my work on until the [original upstream](https://github.com/gschorcht/spi-ch341-usb) is maintained again. I plan on only exposing the gpio pins needed for the [PineDio-USB LoRa](https://wiki.pine64.org/wiki/Pinedio#USB_adapter) dongle after I get all of the internal pins mapped to the pins in this driver.
